# Generated by Django 5.2.14 on 2026-05-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.TextField(max_length=20),
        ),
    ]
