# Generated by Django 5.2.14 on 2026-05-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('color', models.TextField(max_length=20)),
            ],
        ),
    ]
